### ISSUE TITLE
Failing builds on readthedocs

### ISSUE THREAD

**Issue by swvanbuuren** [Linaro/squad#1131] opened 2024-03-21 13:33 UTC
I noticed that the builds on readthedocs have been failing for more than over a year now:
https://readthedocs.org/projects/squad/builds/

This might be worth fixing, since I recon a lot of people will rather read the [generated documentation on readthedocs](https://squad.readthedocs.io/en/latest/index.html), since it's reader friendlier and offers better navigation.

**Comment by swvanbuuren** [comment] 2024-03-21 13:34
@chaws You might want to look into this.

**Comment by mwasilew** [comment] 2024-03-21 13:39
Build failure was fixed with this commit: https://github.com/Linaro/squad/commit/1252194a5e69225781bc69546b530b50a37a1aac
Current issue is that the builds don't get triggered. Let me see if I can find the root cause.

**Comment by mwasilew** [comment] 2024-03-21 13:41
'''
"detail": "This webhook doesn't have a secret configured.\nFor security reasons, webhooks without a secret are no longer permitted.\nFor more information, read our blog post: https://blog.readthedocs.com/security-update-on-incoming-webhooks/."
'''
I don't have access to squad settings in github, so this is something that either @chaws or @terceiro can fix.

**Comment by chaws** [comment] 2024-03-25 19:14
Thanks for reporting @swvanbuuren and for looking into it @mwasilew !
I have now fixed it: https://squad.readthedocs.io/en/latest/install.html#docker-compose-setup

Don't know exactly what happened, but after deleting and recreating it, it worked fine. Plus I had to bump python version here https://github.com/Linaro/squad/commit/8e55e2cc25eb59a0ec1ce0b01bc5ac6d79a75266

**Closed** 2024-03-25 19:15 UTC
