### ISSUE TITLE
Compare Test project selector limited to 50 results

### ISSUE THREAD

**Issue by danrue** [Linaro/squad#319] opened 2018-08-21 16:13 UTC
When I am trying to add additional projects to a compare test view, I am only able to select from the first 50 projects. If my project is beyond the first 50, I am out of luck.

I'm guessing that the javascript API calls are not paging, and just relying on the first page (limit=50) of https://qa-reports.linaro.org/api/projects/.

It's also a bit slow to load. Perhaps an api call for a flat list of 'all projects' is in order.

This may also be true for suite and test loaders, but I don't actually use those as often so I did not test.

**Comment by mwasilew** [comment] 2018-08-21 18:19
Could you give me an example of search string that gives 50+ results? I guess the limit is 'by design'. Displaying more is not very practical.

**Comment by danrue** [comment] 2018-08-21 18:27
Sure. First, log in as admin (so that you can see all projects). Second, try to add any lkft project to this page https://qa-reports.linaro.org/_/comparetest/?project=22&suite=kselftest&test=cgroup_test_core.

For me, it works fine if I browse anonymously. If I browse as myself, the 'lkft' projects are on the second set of 50. Why would we limit squad to 50 projects?

I agree that performance may be an issue, but this call doesn't need project metadata for all of them, so perhaps implementing a light weight way to retrieve all project names and ids would be better than retrieving them from the projects/ endpoint.

**Comment by mwasilew** [comment] 2018-08-21 18:35
projects endpoint is fairly lightweight. So I can imagine getting 'all' results. The problem happens when you try to display say 300 hits (there are currently 115 projects total). The list will be long and will certainly go beyond the screen. 50 is default threshold for any endpoint when using DRF. Once you start typing the list gets shorter.

**Comment by danrue** [comment] 2018-08-21 18:39
I don't follow - what are you suggesting? I don't think there's a workaround here since you can't actually add a project to the list without clicking on it.

**Comment by mwasilew** [comment] 2018-08-21 18:44
![project_filter](https://user-images.githubusercontent.com/618901/44422188-68f0ba00-a57a-11e8-937d-7b02feb2db4f.png)

only mainline (already added) and next are missing from LKFT. Does this help? I meant typing in the search box.

**Comment by danrue** [comment] 2018-08-21 18:48
Ah! OK - here's the issue: I tried typing two things before opening this bug: "lkft", and, "4.". Neither of those strings selects. When I type 'stable' as you have, I do see them.

**Comment by mwasilew** [comment] 2018-08-21 18:55
Let me check if the search also includes group name (probably not). However '4.' should show something.

**Comment by mwasilew** [comment] 2018-08-21 18:57
The search uses "name__startswith" and "slug__startswith". That's why '4.' didn't show anything. I guess this can be fixed.

**Comment by mwasilew** [comment] 2018-08-23 16:50
Closing as #321 was merged.

**Closed by mwasilew** 2018-08-23 16:50 UTC
Labels: bug
