### ISSUE TITLE
error accessing /api/schema/

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squad#799] opened 2020-07-29 08:17 UTC
```
File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/usr/lib/python3/dist-packages/django/core/handlers/base.py" in _get_response
  217.                 response = self.process_exception_by_middleware(e, request)

File "/usr/lib/python3/dist-packages/django/core/handlers/base.py" in _get_response
  215.                 response = response.render()

File "/usr/lib/python3/dist-packages/django/template/response.py" in render
  107.             self.content = self.rendered_content

File "/usr/lib/python3/dist-packages/rest_framework/response.py" in rendered_content
  72.         ret = renderer.render(self.data, accepted_media_type, context)

File "/usr/lib/python3/dist-packages/rest_framework/renderers.py" in render
  1036.         structure = self.get_structure(data)

File "/usr/lib/python3/dist-packages/rest_framework/renderers.py" in get_structure
  1016.                 'title': data.title,
```

**Comment by mwasilew** [comment] 2020-07-29 08:17
This is probably some mismatch in library versions

**Comment by chaws** [comment] 2020-07-29 20:05
I honestly don't know what happened, but I couldn't reproduce that in any environment dev/testing/staging/production. In development, I tried current docker image, then 1.16.1 and 1.16 and didn't see this error :(

I've cleared it in Sentry so we'll be warned if this happens again. I'm closing this issue as well and will keep an eye if it happens in the future

**Closed by chaws** 2020-07-29 20:05 UTC
