### ISSUE TITLE
Wrong URL to Lava with multinode Jobs

### ISSUE THREAD

**Issue by feine-moehre** [Linaro/squad#533] opened 2019-05-17 11:14 UTC
I submit a multinode job through squad to lava. 
This is a screenshot of the squad administration. 
![image](https://user-images.githubusercontent.com/50700938/57924205-d2e98600-78a4-11e9-8943-732cf483462c.png)
The job ids are 1516.0 and 1516.1. The highlighted link is `http://<lava-instance>/scheduler/job/['1516.0', '1516.1']` which is wrong. Lava (2019-04) can not handle this link because it can display only one job.

**Comment by mwasilew** [comment] 2019-05-17 11:42
Yep, that's a known issue. The fix should be simple though. We'll point to the 'master' job in multinode. Would that work for you?

**Comment by feine-moehre** [comment] 2019-05-17 11:50
This would disregard all test cases of the other subjobs. In my testcases I implement different testcases based on the role. 
For example: I have two boards with an uart connection between them. The sender (master job) has testcases to check if transmission is ok und as fast as expected. The receiver ( one other job) checks transmitted data size and correctness.

Your proposal would skip the receiver tests. It is possible to fetch every job individually?

**Comment by mwasilew** [comment] 2019-05-17 11:55
Hmm, IIRC master collects all results in multinode job. At least this was the case some time ago. When you call results.get_testjob_results_* in LAVA on the master job (in your case it's probably 1516) it should fetch all results. I'll try that locally and get back to you.

**Comment by mwasilew** [comment] 2019-05-17 12:45
I was wrong. Each result has to be fetched separately. I'll come up with some fix.

**Comment by mwasilew** [comment] 2019-05-17 12:54
@terceiro the problem is in this line: https://github.com/Linaro/squad/blob/master/squad/ci/models.py#L137
In case of multinode lava returns list of job IDs instead of just one. I propose we 'clone' TestJob object in squad and assign subsequent IDs to cloned objects. I'm not sure how it will react to potential resubmission (might grow pretty quickly) and representation in Build/TestRun (should not cause any issues). Any other ideas?

**Comment by terceiro** [comment] 2019-05-17 14:34
@mwasilew so do yoy think that we can ignore the test definition itself on the squad side, and detect multinode jobs just by the fact that submit() returns a list intead of a single job id? this would be the ideal IMO so we don't need to care about the contents of the submission.

**Comment by mwasilew** [comment] 2019-05-17 14:39
It's not easy to detect multinode by contents of submission. We would have to parse the YAML and I don't think this is a good idea. In case of multinode LAVA will always return IDs of all jobs. We can use this fact to support multinode.

**Comment by mwasilew** [comment] 2019-05-20 10:33
My initial attempt: https://github.com/Linaro/squad/pull/535
This should work. The only flaw I can see is the fact you can individually resubmit each of the multinode jobs. Each resubmission will result in set of jobs (new multinode job). I'm not sure if this problem is important enough to be fixed in this PR.

One more thing I noticed is we're not fully compliant with our own spec for CI backend API. resubmit() should return ID of the re-submitted job "as provided by the backend". Right now we're returning TestJob objects. I didn't change this yet but I don't see this object used anywhere in the code. So fixing the behaviour in all backend implementations should be harmless (in theory).

**Comment by mwasilew** [comment] 2019-06-03 12:49
This issue should be fixed with #535

**Closed by mwasilew** 2019-06-03 12:49 UTC
