### ISSUE TITLE
Squad not displaying number of test runs and number of pass/fail

### ISSUE THREAD

**Issue by axelnxp** [Linaro/squad#457] opened 2019-01-22 10:12 UTC
The issue appeared on 0.58. Now upgraded to 0.60.

if I go to /group/project in "latest builds", Squad doesn't display the number of test runs, number of pass/fail. If I open one of these builds, I can see all the test I ran, test runs, pass/fail...
It works for some builds but not all of them. 
Tests are submitted to LAVA through /api/submitjob/ API.

I deleted some of builds and test runs because they were not relevant. Maybe it broke something ?

In administration page, I checked projectstatuses, the statuses of buggy builds show no test results. 
The "last updated" field is empty for every buggy build. 

Note that some builds appeared while previous builds were not finished. 

Please ask if you need more information.

**Comment by axelnxp** [comment] 2019-02-08 09:30
The issue reappeared on a new installation of SQUAD (0.61).
I have more details this time:
1 test has been submitted for a build. The test finished so the build has been considered finished by SQUAD.
But, I submitted other tests for the same build, but the project is still considered as finished, so it doesn't display new test results on project summary page. But if I open the build, I can see it recorded every test runs, results etc... So I set the buidl statuses to unfinished to see if when last tests are finished, the results will be updated on project summary page.

Hope this helps.

**Comment by mwasilew** [comment] 2019-02-08 09:39
On Fri, 8 Feb 2019 at 09:31, Axel Le Bourhis <notifications@github.com> wrote:
>
> The issue reappeared on a new installation of SQUAD (0.61).
> I have more details this time:
> 1 test has been submitted for a build. The test finished so the build has been considered finished by SQUAD.
> But, I submitted other tests for the same build, but the project is still considered as finished, so it doesn't display new test results on project summary page. But if I open the build, I can see it recorded every test runs, results etc... So I set the buidl statuses to unfinished to see if when last tests are finished, the results will be updated on project summary page.
>

This sounds like the status update task is only executed on
'unfinished' builds. Could you share logs from worker? I'll try to
reproduce this locally.

milosz

**Comment by axelnxp** [comment] 2019-02-08 10:31
Ok so now it has been updated. 
I think it's because is manually set back the project to unfinished state.
Maybe it would be nice to automate that ? 

I give you the log with some comments in it, so you can see different steps.

[squad-worker.log](https://github.com/Linaro/squad/files/2844673/squad-worker.log)

Hope this helps

**Comment by terceiro** [comment] 2019-02-11 11:19
there are too problems here:

1) the count of pass/fail/etc is cached so that we don't  need to recalculate that every time. so if you delete builds by hand you need to force that recalculation (it happens on new test results, but otherwise I don't think we have an interface to trigger that from the UI).

2) the second notification did not go out because of an excess of RAM usage. I have an open pull request to solve that (#474), but other than that.

**Comment by chaws** [comment] 2019-05-07 22:55
@axelnxp I'm closing this for now. Please let us know if you have any further questions :)

**Closed by chaws** 2019-05-07 22:55 UTC
