### ISSUE TITLE
Install squad on Debian stretch

### ISSUE THREAD

**Issue by feine-moehre** [Linaro/squad#531] opened 2019-05-16 10:34 UTC
I try to install squad on a debian stretch machine. While starting `squad` for the first time, I got this `ImportError`. Installing on ubuntu cosmic works fine.

```
$ squad
Traceback (most recent call last):
  File "/usr/local/bin/squad", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/squad/run/__init__.py", line 50, in main
    manage()
  File "/usr/local/lib/python3.5/dist-packages/squad/manage.py", line 14, in main
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 327, in execute
    self.check()
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/lib/python3/dist-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/lib/python3/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/lib/python3/dist-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/lib/python3/dist-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/usr/lib/python3/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib/python3/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/dist-packages/squad/urls.py", line 51, in <module>
    url(r'^api/', include('squad.api.urls')),
  File "/usr/lib/python3/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/dist-packages/squad/api/urls.py", line 2, in <module>
    from rest_framework.schemas import get_schema_view
ImportError: cannot import name 'get_schema_view'
```
Is there a dependency missing or is this a debian stretch specific bug?

**Comment by mwasilew** [comment] 2019-05-16 10:52
Strange, I can't reproduce this issue. I just installed squad in fresh debian:stretch container. The only issue I had was missing postgres. Out installation instructions are missing this bit. I had to add:
```apt-get install postgresql postgresql-server-dev-9.6```
After this was done, squad installation completed without any issues and running ```squad``` just worked. @terceiro any idea what went wrong?

**Comment by terceiro** [comment] 2019-05-16 13:12
I did the same here, and just worked except the postresql indeed (already added the missing package to the instructions).

@feine-moehre can you give a little more detail on what steps exactly you performed on your stretch box?

**Comment by feine-moehre** [comment] 2019-05-16 13:45
After fiddle around with dependencies, I hopefully solve the issue.
```
$ rmadison python3-psycopg2
python3-psycopg2 | 2.6.2-1       | stable     | amd64, arm64, armel, armhf, i386, mips, mips64el, mipsel, ppc64el, s390x
```
Version 2.6.x is stable in debian stretch. But this version will cause the error above. Upgrading psycopg2 via pip to 2.8.2 is the solution.

Can you clearify the pitfall? Please specify the required version and add it to the documentation.

**Comment by chaws** [comment] 2019-08-08 19:35
@feine-moehre , I think the issues were addressed by Antonio. I fired up a fresh stretch VM, installed everything and ran squad without any issues. Did you get yours running as well?

**Comment by chaws** [comment] 2019-08-15 11:41
I think this issue was solved. Please re-open if something similar happen again.

**Closed by chaws** 2019-08-15 11:41 UTC
